print("Введите a:" )
a = float(input())
print("Введите b:" )
b = float(input())
print("a + b = ",a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)
print("a / b = ", a / b)
print("a ^ b = ", a**b)
print("Остаток от деления a на b = ", a % b)
print("Целочисленное деление a на b = ", a // b)